name: ewelink
description: A modern eWelink device manager with glassmorphic UI.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5
  crypto: ^3.0.3
  uuid: ^3.0.7
  intl: ^0.18.0
  path_provider: ^2.0.15
  glossy: ^0.0.5
  flutter_animate: ^4.5.2
  lottie: ^3.0.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
